### ISSUE TITLE
Rechtschreibfehler in Flyer korrigieren

### ISSUE THREAD

**Issue by dersch81** [freifunk-darmstadt/pr#6]
In dem Generic.pdf und CommercialPlaces.pdf Flyer ist jeweils der gleiche Rechtschreibfehler:

"Freifunk Darmstadt hilft dir dabei, ein passendes Gerät zu finden und einzurrichten"

Es muss "einrichten" heissen.

**Comment by mweinelt** [comment]
einzurichten sollte schon korrekt sein, nur das doppelte r muss weg, oder?

**Comment by dersch81** [comment]
Hi Hexa,

Ja richtig. Grüße Dirk

hexa- <notifications@github.com> schrieb am Mi., 7. Okt. 2015 21:48:

**Comment by mweinelt** [comment]
Danke
